
export const Data = [
  { isoCode: "AF", country: "Afghanistan" },
  { isoCode: "AL", country: "Albania" },
  { isoCode: "DZ", country: "Algeria" },
  { isoCode: "AS", country: "American Samoa" },
  { isoCode: "AD", country: "Andorra" },
  { isoCode: "AO", country: "Angola" },
  { isoCode: "AI", country: "Anguilla" },
  { isoCode: "AQ", country: "Antarctica" },
  { isoCode: "AG", country: "Antigua and Barbuda" },
  { isoCode: "AR", country: "Argentina" },
  { isoCode: "AM", country: "Armenia" },
  { isoCode: "AW", country: "Aruba" },
  { isoCode: "AC", country: "Ascension Island" },
  { isoCode: "AU", country: "Australia" },
  { isoCode: "AT", country: "Austria" },
  { isoCode: "AZ", country: "Azerbaijan" },
  { isoCode: "BS", country: "Bahamas" },
  { isoCode: "BH", country: "Bahrain" },
  { isoCode: "BD", country: "Bangladesh" },
  { isoCode: "BB", country: "Barbados" },
  { isoCode: "BY", country: "Belarus" },
  { isoCode: "BE", country: "Belgium" },
  { isoCode: "BZ", country: "Belize" },
  { isoCode: "BJ", country: "Benin" },
  { isoCode: "BM", country: "Bermuda" },
  { isoCode: "BT", country: "Bhutan" },
  { isoCode: "BO", country: "Bolivia" },
  { isoCode: "BA", country: "Bosnia and Herzegovina" },
  { isoCode: "BW", country: "Botswana" },
  { isoCode: "BR", country: "Brazil" },
  { isoCode: "VG", country: "British Virgin Islands" },
  { isoCode: "BN", country: "Brunei" },
  { isoCode: "BG", country: "Bulgaria" },
  { isoCode: "BF", country: "Burkina Faso" },
  { isoCode: "MM", country: "Burma (Myanmar)" },
  { isoCode: "BI", country: "Burundi" },
  { isoCode: "KH", country: "Cambodia" },
  { isoCode: "CM", country: "Cameroon" },
  { isoCode: "CA", country: "Canada" },
  { isoCode: "CV", country: "Cape Verde" },
  { isoCode: "KY", country: "Cayman Islands" },
  { isoCode: "CF", country: "Central African Republic" },
  { isoCode: "TD", country: "Chad" },
  { isoCode: "CL", country: "Chile" },
  { isoCode: "CN", country: "China" },
  { isoCode: "CX", country: "Christmas Island" },
  { isoCode: "CC", country: "Cocos (Keeling) Islands" },
  { isoCode: "CO", country: "Colombia" },
  { isoCode: "KM", country: "Comoros" },
  { isoCode: "CG", country: "Congo" },
  { isoCode: "CK", country: "Cook Islands" },
  { isoCode: "CR", country: "Costa Rica" },
  { isoCode: "HR", country: "Croatia" },
  { isoCode: "CU", country: "Cuba" },
  { isoCode: "CY", country: "Cyprus" },
  { isoCode: "CZ", country: "Czech Republic" },
  { isoCode: "CD", country: "Democratic Republic of the Congo" },
  { isoCode: "DK", country: "Denmark" },
  { isoCode: "DG", country: "Diego Garcia" },
  { isoCode: "DJ", country: "Djibouti" },
  { isoCode: "DM", country: "Dominica" },
  { isoCode: "DO", country: "Dominican Republic" },
  { isoCode: "EC", country: "Ecuador" },
  { isoCode: "EG", country: "Egypt" },
  { isoCode: "SV", country: "El Salvador" },
  { isoCode: "GQ", country: "Equatorial Guinea" },
  { isoCode: "ER", country: "Eritrea" },
  { isoCode: "EE", country: "Estonia" },
  { isoCode: "ET", country: "Ethiopia" },
  { isoCode: "FK", country: "Falkland Islands" },
  { isoCode: "FO", country: "Faroe Islands" },
  { isoCode: "FJ", country: "Fiji" },
  { isoCode: "FI", country: "Finland" },
  { isoCode: "FR", country: "France" },
  { isoCode: "GF", country: "French Guiana" },
  { isoCode: "PF", country: "French Polynesia" },
  { isoCode: "GA", country: "Gabon" },
  { isoCode: "GM", country: "Gambia" },
  { isoCode: "GE", country: "Georgia" },
  { isoCode: "DE", country: "Germany" },
  { isoCode: "GH", country: "Ghana" },

  { isoCode: "GI", country: "Gibraltar" },

  { isoCode: "GR", country: "Greece" },

  { isoCode: "GL", country: "Greenland" },

  { isoCode: "GD", country: "Grenada" },

  { isoCode: "GP", country: "Guadeloupe" },
  { isoCode: "GU", country: "Guam" },

  { isoCode: "GT", country: "Guatemala" },

  { isoCode: "GN", country: "Guinea" },

  { isoCode: "GW", country: "Guinea-Bissau" },

  { isoCode: "GY", country: "Guyana" },
  { isoCode: "HT", country: "Haiti" },

  { isoCode: "VA", country: "Holy See (Vatican City)" },

  { isoCode: "HN", country: "Honduras" },

  { isoCode: "HK", country: "Hong Kong" },

  { isoCode: "HU", country: "Hungary" },

  { isoCode: "IS", country: "Iceland" },

  { isoCode: "IN", country: "India" },

  { isoCode: "ID", country: "Indonesia" },
  { isoCode: "IR", country: "Iran" },
  { isoCode: "IQ", country: "Iraq" },
  { isoCode: "IE", country: "Ireland" },
  { isoCode: "IM", country: "Isle of Man" },
  { isoCode: "IL", country: "Israel" },
  { isoCode: "IT", country: "Italy" },
  { isoCode: "CI", country: "Ivory Coast (Côte d'Ivoire)" },
  { isoCode: "JM", country: "Jamaica" },
  { isoCode: "JP", country: "Japan" },
  { isoCode: "JE", country: "Jersey" },
  { country: "Jordan", isoCode: "JO" },
  { country: "Kazakhstan", isoCode: "KZ" },
  { country: "Kenya", isoCode: "KE" },
  { country: "Kiribati", isoCode: "KI" },
  { country: "Kuwait", isoCode: "KW" },
  { country: "Kyrgyzstan", isoCode: "KG" },
  { country: "Laos", isoCode: "LA" },
  { country: "Latvia", isoCode: "LV" },
  { country: "Lebanon", isoCode: "LB" },
  { country: "Lesotho", isoCode: "LS" },
  { country: "Liberia", isoCode: "LR" },
  { country: "Libya", isoCode: "LY" },
  { country: "Liechtenstein", isoCode: "LI" },
  { country: "Lithuania", isoCode: "LT" },
  { country: "Luxembourg", isoCode: "LU" },
  { country: "Macau", isoCode: "MO" },
  { country: "Macedonia", isoCode: "MK" },
  { country: "Madagascar", isoCode: "MG" },
  { country: "Malawi", isoCode: "MW" },
  { country: "Malaysia", isoCode: "MY" },
  { country: "Maldives", isoCode: "MV" },
  { country: "Mali", isoCode: "ML" },
  { country: "Malta", isoCode: "MT" },
  { country: "Marshall Islands", isoCode: "MH" },
  { country: "Martinique", isoCode: "MQ" },
  { country: "Mauritania", isoCode: "MR" },
  { country: "Mauritius", isoCode: "MU" },
  { country: "Mayotte", isoCode: "YT" },
  { country: "Mexico", isoCode: "MX" },
  { country: "Micronesia", isoCode: "FM" },
  { country: "Moldova", isoCode: "MD" },
  { country: "Monaco", isoCode: "MC" },
  { country: "Mongolia", isoCode: "MN" },
  { country: "Montenegro", isoCode: "ME" },
  { country: "Montserrat", isoCode: "MS" },
  { country: "Morocco", isoCode: "MA" },
  { country: "Mozambique", isoCode: "MZ" },
  { country: "Namibia", isoCode: "NA" },
  { country: "Nauru", isoCode: "NR" },
  { country: "Nepal", isoCode: "NP" },
  { country: "Netherlands", isoCode: "NL" },
  { country: "Netherlands Antilles", isoCode: "AN" },
  { country: "New Caledonia", isoCode: "NC" },
  { country: "New Zealand", isoCode: "NZ" },
  { country: "Nicaragua", isoCode: "NI" },
  { country: "Niger", isoCode: "NE" },
  { country: "Nigeria", isoCode: "NG" },
  { country: "Niue", isoCode: "NU" },
  { country: "Norfolk Island", isoCode: "NF" },
  { country: "North Korea", isoCode: "KP" },
  { country: "Northern Mariana Islands", isoCode: "MP" },
  { country: "Norway", isoCode: "NO" },
  { country: "Oman", isoCode: "OM" },
  { country: "Pakistan", isoCode: "PK" },
  { country: "Palau", isoCode: "PW" },
  { country: "Palestine", isoCode: "PS" },
  { country: "Panama", isoCode: "PA" },
  { country: "Papua New Guinea", isoCode: "PG" },
  { country: "Paraguay", isoCode: "PY" },
  { country: "Peru", isoCode: "PE" },
  { country: "Philippines", isoCode: "PH" },
  { country: "Pitcairn", isoCode: "PN" },
  { country: "Poland", isoCode: "PL" },
  { country: "Portugal", isoCode: "PT" },
  { country: "Puerto Rico", isoCode: "PR" },
  { country: "Qatar", isoCode: "QA" },
  { country: "Réunion", isoCode: "RE" },
  { country: "Romania", isoCode: "RO" },
  { country: "Russia", isoCode: "RU" },
  { country: "Rwanda", isoCode: "RW" },
  { country: "Saint Barthélemy", isoCode: "BL" },
  { country: "Saint Helena", isoCode: "SH" },
  { country: "Saint Kitts and Nevis", isoCode: "KN" },
  { country: "Saint Lucia", isoCode: "LC" },
  { country: "Saint Martin", isoCode: "MF" },
  { country: "Saint Pierre and Miquelon", isoCode: "PM" },
  { country: "Saint Vincent and the Grenadines", isoCode: "VC" },
  { country: "Samoa", isoCode: "WS" },
  { country: "San Marino", isoCode: "SM" },
  { country: "São Tomé and Príncipe", isoCode: "ST" },
  { country: "Saudi Arabia", isoCode: "SA" },
  { country: "Senegal", isoCode: "SN" },
  { country: "Serbia", isoCode: "RS" },
  { country: "Seychelles", isoCode: "SC" },
  { country: "Sierra Leone", isoCode: "SL" },
  { country: "Singapore", isoCode: "SG" },
  { country: "Sint Maarten", isoCode: "SX" },
  { country: "Slovakia", isoCode: "SK" },
  { country: "Slovenia", isoCode: "SI" },
  { country: "Solomon Islands", isoCode: "SB" },
  { country: "Somalia", isoCode: "SO" },
  { country: "South Africa", isoCode: "ZA" },
  { country: "South Georgia and the South Sandwich Islands", isoCode: "GS" },
  { country: "South Korea", isoCode: "KR" },
  { country: "South Sudan", isoCode: "SS" },
  { country: "Spain", isoCode: "ES" },
  { country: "Sri Lanka", isoCode: "LK" },
  { country: "Sudan", isoCode: "SD" },
  { country: "Suriname", isoCode: "SR" },
  { country: "Swaziland", isoCode: "SZ" },
  { country: "Sweden", isoCode: "SE" },
  { country: "Switzerland", isoCode: "CH" },
  { country: "Syria", isoCode: "SY" },
  { country: "Taiwan", isoCode: "TW" },
  { country: "Tajikistan", isoCode: "TJ" },
  { country: "Tanzania", isoCode: "TZ" },
  { country: "Thailand", isoCode: "TH" },
  { country: "Timor-Leste", isoCode: "TL" },
  { country: "Togo", isoCode: "TG" },
  { country: "Tokelau", isoCode: "TK" },
  { country: "Tonga", isoCode: "TO" },
  { country: "Trinidad and Tobago", isoCode: "TT" },
  { country: "Tunisia", isoCode: "TN" },
  { country: "Turkey", isoCode: "TR" },
  { country: "Turkmenistan", isoCode: "TM" },
  { country: "Turks and Caicos Islands", isoCode: "TC" },
  { country: "Tuvalu", isoCode: "TV" },
  { country: "Uganda", isoCode: "UG" },
  { country: "Ukraine", isoCode: "UA" },
  { country: "United Arab Emirates", isoCode: "AE" },
  { country: "United Kingdom", isoCode: "UK" },
  { country: "United States", isoCode: "US" },
  { country: "Uruguay", isoCode: "UY" },
  { country: "Uzbekistan", isoCode: "UZ" },
  { country: "Vanuatu", isoCode: "VU" },
  { country: "Venezuela", isoCode: "VE" },
  { country: "Vietnam", isoCode: "VN" },
  { country: "Wallis and Futuna", isoCode: "WF" },
  { country: "Western Sahara", isoCode: "EH" },
  { country: "Yemen", isoCode: "YE" },
  { country: "Zambia", isoCode: "ZM" },
  { country: "Zimbabwe", isoCode: "ZW" },
]
